# Site wide configuration

title: Patrick Diehl
locale: en_US
description: Peronal website 
  #logo: site-logo.png
search: true
url: https://www.diehlpk.de

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-seo-tag

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor", "data" ]

google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

# Site owner
owner:
  name: Patrick Diehl
  avatar: avatar.png
  email: me@diehlpk.de
  disqus-shortname:
  cv: https://www.diehlpk.de/assets/cv.pdf
  twitter: diehlpk
  facebook: #username
  github: diehlpk
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: patrickdiehl
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  orcid: https://orcid.org/0000-0003-3922-8419
  gscholar: https://scholar.google.com/citations?user=TapM4vAAAAAJ&hl=en
  arxiv: https://arxiv.org/a/0000-0003-3922-8419.html
  calendar: https://www.diehlpk.de/calendar/
  youtube: UCzNHuPcTiMMltS5IVCRHwHA
  dblp: https://dblp.uni-trier.de/pid/187/0682.html?q=Patrick%20Diehl
  google:
    plus: #username
    analytics: 
    verify:
    ad-client:
    ad-slot:
  bing-verify:
