long:
	latexmk -pdflatex=lualatex -pdf long.tex &&  cp long.pdf ../../assets/cv.pdf

nsf:
	latexmk -pdflatex=lualatex -pdf nsf.tex &&  cp nsf.pdf ../../assets/nsf.pdf

clean:
	latexmk -C

showLong:
	evince long.pdf &

